@baseUrl=http://localhost:3000/auths

### Try to login user
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "admin@vinci.be",
  "password": "admin"
}

### Try to login user
POST {{baseUrl}}/login
Content-Type: application/json

{

}