@baseUrl=http://localhost:8080/auths

### Try to login user
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "admin@vinci.be",
  "password": "admin"
}

### Try to login user
POST {{baseUrl}}/login
Content-Type: application/json

{

}

### verify token
POST {{baseUrl}}/login
Content-Type: application/json
Authorization: {{response.body.token}}

{
  "email": "admin@vinci.be",
    "password": "admin"
}