@authsUrl=http://localhost:3000/auths
@companiesUrl=http://localhost:3000/companies

### Try to login user
POST {{authsUrl}}/login
Content-Type: application/json

{
  "email": "raphael.baroni@vinci.be",
  "password": "Prof24,z"
}

> {%
  client.global.set("token", response.body.token);
%}

### Get all companies
GET {{companiesUrl}}

### Blacklist a company
POST {{companiesUrl}}/2/blacklist
Authorization: {{token}}
Content-Type: application/json

{
  "reason": "This company is a scam"
}

