@authsUrl=http://localhost:3000/auths
@companiesUrl=http://localhost:3000/companies

### Try to login user
POST {{authsUrl}}/login
Content-Type: application/json

{
  "email": "raphael.baroni@vinci.be",
  "password": "Prof24,z"
}

> {%
  client.global.set("token", response.body.token);
%}

### Get all companies
GET {{companiesUrl}}

### Blacklist a company
POST {{companiesUrl}}/4/blacklist
Authorization: {{token}}
Content-Type: application/json

{
  "reason": "This company is a scam"
}

### Create a company
POST {{companiesUrl}}
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Company 1",
  "description": "This is a company",
  "address": "Rue de la Loi 16, 1000 Bruxelles",
  "phone": "02 123 45 67"
}

