@authsUrl=http://localhost:3000/auths
@contactUrl=http://localhost:3000/contact

### Try to login user
POST {{authsUrl}}/login
Content-Type: application/json

{
  "email": "julien.remmery@student.vinci.be",
  "password": "test"
}

> {%
  client.global.set("token", response.body.token);
%}

### Refuse a contact
POST {{contactUrl}}/2/refuse
Content-Type: application/json
Authorization: {{token}}

{
  "refusalReason": "L'entreprise n'a plus besoin d'étudiants."
}

### Add a contact
POST {{contactUrl}}/add
Content-Type: application/json
Authorization: {{token}}

{
  "idCompany": 1
}

### Get list of contacts
GET {{contactUrl}}
Content-Type: application/json
Authorization: {{token}}

### unfollow a contact
POST {{contactUrl}}/1/unfollow
Content-Type: application/json
Authorization : {{token}}

//Faire la requete meetContact
