@authsUrl=http://localhost:3000/auths
@contactUrl=http://localhost:3000/internships

### Try to login user
POST {{authsUrl}}/login
Content-Type: application/json

{
  "email": "hadjera.emroska@student.vinci.be",
  "password": "12345678"
}

> {%
  client.global.set("token", response.body.token);
%}

### Try to get all internships
GET {{contactUrl}}
Authorization: {{token}}

### Try to add an internship
POST {{contactUrl}}
Authorization: {{token}}
Content-Type: application/json

{
  "idStudent": 14,
  "idCompany": 3,
  "idContact": 33,
  "internshipProject": "Internship 1",
  "idInternshipSupervisor": 8,
  "signatureDate": "2021-01-01"
}